import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
import { validateTaxonomy } from '../../src/domain/taxonomy-validator.js';
const nodes=JSON.parse(fs.readFileSync('data/taxonomy-nodes.json')); const links=JSON.parse(fs.readFileSync('data/taxonomy-links.json')); const aliases=JSON.parse(fs.readFileSync('data/aliases.json')); const version=JSON.parse(fs.readFileSync('data/taxonomy-version.json'));
const invalid=(n=nodes,l=links,a=aliases,v=version)=>validateTaxonomy(structuredClone(n),structuredClone(l),structuredClone(a),structuredClone(v)).valid;
test('corpus réel valide',()=>{const r=validateTaxonomy(nodes,links,aliases,version); assert.equal(r.valid,true); assert.deepEqual(r.stats,{nodeCount:28,structureNodeCount:8,capturableNodeCount:20,primaryLinkCount:27,secondaryLinkCount:2});});
test('identifiant dupliqué',()=>assert.equal(invalid([...nodes,nodes[0]]),false));
test('parent inexistant',()=>{const n=structuredClone(nodes); n[1].parentId='missing'; assert.equal(invalid(n),false);});
test('cycle',()=>{const n=structuredClone(nodes); n.find(x=>x.id==='beer').parentId='west-coast-ipa'; assert.equal(invalid(n),false);});
test('coordonnées invalides',()=>{const n=structuredClone(nodes); n[0].position.x='x'; assert.equal(invalid(n),false);});
test('lien vers nœud inexistant',()=>{const l=structuredClone(links); l[0].targetId='missing'; assert.equal(invalid(nodes,l),false);});
test('incohérence parentId et lien principal',()=>{const l=structuredClone(links); l.find(x=>x.targetId==='west-coast-ipa').sourceId='ipa'; assert.equal(invalid(nodes,l),false);});
test('alias ambigu',()=>{const a=structuredClone(aliases); a['american-ipa']=['APA']; assert.equal(invalid(nodes,links,a),false);});
test('compteur taxonomique incorrect',()=>{const v=structuredClone(version); v.nodeCount=99; assert.equal(invalid(nodes,links,aliases,v),false);});
