import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import { computeVisibleMapState } from '../../src/domain/map-visibility.js';
const nodes=JSON.parse(fs.readFileSync('data/taxonomy-nodes.json')); const links=JSON.parse(fs.readFileSync('data/taxonomy-links.json'));
const ids=a=>new Set(a.map(x=>x.id)); const linkIds=a=>new Set(a.map(x=>x.id));
test('carte vide',()=>{const s=computeVisibleMapState(nodes,links,new Set()); assert.equal(s.visibleNodes.length,8); assert.equal([...s.visibleNodes].filter(n=>n.functionalType==='capturable').length,0); assert.equal(s.interactiveNodeIds.size,0);});
test('West Coast IPA seule',()=>{const s=computeVisibleMapState(nodes,links,new Set(['west-coast-ipa'])); const v=ids(s.visibleNodes), l=linkIds(s.visibleLinks); assert(v.has('west-coast-ipa')); assert(!v.has('ipa')); assert(!v.has('american-ipa')); assert(!v.has('new-england-ipa')); ['primary-beer-fermentation-high','primary-fermentation-high-family-pale-ale-ipa','primary-family-pale-ale-ipa-ipa','primary-ipa-american-ipa','primary-american-ipa-west-coast-ipa'].forEach(id=>assert(l.has(id))); assert.deepEqual([...s.interactiveNodeIds],['west-coast-ipa']);});
test('American IPA seule',()=>{const s=computeVisibleMapState(nodes,links,new Set(['american-ipa'])); const v=ids(s.visibleNodes), l=linkIds(s.visibleLinks); assert(v.has('american-ipa')); assert(!v.has('ipa')); assert(!v.has('west-coast-ipa')); assert(!v.has('new-england-ipa')); assert(l.has('primary-american-ipa-west-coast-ipa')); assert(l.has('primary-american-ipa-new-england-ipa'));});
test('White IPA seule',()=>{const s=computeVisibleMapState(nodes,links,new Set(['white-ipa'])); const v=ids(s.visibleNodes), l=linkIds(s.visibleLinks); assert(v.has('white-ipa')); assert(!v.has('witbier')); assert(l.has('secondary-white-ipa-witbier')); assert(!s.interactiveNodeIds.has('witbier'));});
test('India Pale Lager seule',()=>{const s=computeVisibleMapState(nodes,links,new Set(['india-pale-lager'])); const v=ids(s.visibleNodes), l=linkIds(s.visibleLinks); assert(v.has('india-pale-lager')); assert(!v.has('ipa')); assert(l.has('secondary-india-pale-lager-ipa')); assert(!s.interactiveNodeIds.has('ipa'));});
test('géométrie stable',()=>{const before=JSON.stringify(nodes.map(n=>n.position)); const a=computeVisibleMapState(nodes,links,new Set(['west-coast-ipa'])); const b=computeVisibleMapState(nodes,links,new Set(['american-ipa'])); assert.equal(JSON.stringify(nodes.map(n=>n.position)),before); assert.deepEqual(computeVisibleMapState(nodes,links,new Set(['west-coast-ipa'])),a); assert.equal(nodes.find(n=>n.id==='west-coast-ipa').position.x,1980); assert(b);});
