import { SCENARIOS } from '../config.js';
import { buildSearchIndex, findDebugStyleMatches } from '../domain/search.js';

export function getScenarioFromUrl(search, fallback = 'empty') { const scenario = new URLSearchParams(search).get('scenario') ?? fallback; return Object.hasOwn(SCENARIOS, scenario) ? scenario : fallback; }

export function createDebugPanel(container, data, stateStore) {
  const { nodes, aliases, discovered, onScenario, onReveal, onPreviewReveal, onHide, onReset, onSelect, onClearSelection, onToggleExplored, onReducedMotion } = stateStore;
  const searchIndex = buildSearchIndex(nodes, aliases); const panel = document.createElement('aside'); panel.className = 'debug-panel'; panel.innerHTML = '<h2>Outils développeur V0.2.2</h2><p class="debug-versions">App 0.2.2 — Taxonomie 0.1.1-prototype.2</p>';
  const select = document.createElement('select'); select.setAttribute('aria-label','Scénario actif'); for (const key of Object.keys(SCENARIOS)){ const o=document.createElement('option'); o.value=key; o.textContent=key; select.append(o);} select.value=stateStore.scenario; select.addEventListener('change',()=>onScenario(select.value)); panel.append(select);
  const section=document.createElement('section'); section.innerHTML='<h3>Révéler un style de test</h3>'; const input=document.createElement('input'); input.type='text'; input.placeholder='West Coast IPA ou WCIPA'; input.setAttribute('aria-label','Nom ou alias du style'); const actions=document.createElement('div'); actions.className='debug-actions'; const reveal=button('Révéler'); const preview=button('Aperçu révélation'); const hide=button('Masquer'); actions.append(reveal,preview,hide); const message=document.createElement('p'); const ambiguousList=document.createElement('div'); section.append(input,actions,message,ambiguousList); panel.append(section);
  const lab=document.createElement('section'); lab.innerHTML='<h3>Laboratoire visuel</h3>'; const styleSelect=document.createElement('select'); styleSelect.setAttribute('aria-label','Style du laboratoire visuel'); nodes.filter(n=>n.functionalType==='capturable').forEach(n=>{const o=document.createElement('option'); o.value=n.id; o.textContent=n.name; styleSelect.append(o);}); const labActions=document.createElement('div'); labActions.className='debug-actions'; const selectStyle=button('Sélectionner'); const clear=button('Retirer sélection'); const explored=button('Basculer approfondi'); const reduce=button('Réduire animations'); reduce.setAttribute('aria-pressed','false'); labActions.append(selectStyle,clear,explored,reduce); const visualState=document.createElement('pre'); visualState.className='visual-state'; lab.append(styleSelect,labActions,visualState); panel.append(lab);
  const reset=button('Tout réinitialiser'); reset.addEventListener('click',()=>{onReset(); message.textContent='Découvertes de test réinitialisées.';}); panel.append(reset); const count=document.createElement('p'); const list=document.createElement('div'); panel.append(count,list);
  function button(t){const b=document.createElement('button'); b.textContent=t; return b;} function match(){ const result=findDebugStyleMatches(input.value,searchIndex); ambiguousList.replaceChildren(); return result; }
  function renderAmbiguous(matches, cb){ ambiguousList.replaceChildren(); for(const node of matches){ const b=button(node.name); b.addEventListener('click',()=>cb(node)); ambiguousList.append(b);} }
  function revealNode(node){ if(discovered.has(node.id)){message.textContent='Ce style est déjà visible.'; return;} onReveal(node.id); message.textContent=`${node.name} révélée pour le test.`; }
  reveal.addEventListener('click',()=>{ const r=match(); if(r.status==='empty') message.textContent='Saisie vide.'; if(r.status==='none') message.textContent='Aucun style ne correspond.'; if(r.status==='single') revealNode(r.matches[0]); if(r.status==='ambiguous'){message.textContent='Plusieurs styles correspondent.'; renderAmbiguous(r.matches,revealNode);} });
  preview.addEventListener('click',()=>{ const r=match(); if(r.status==='single'){ onPreviewReveal(r.matches[0].id); message.textContent=`Aperçu lancé pour ${r.matches[0].name}.`; } else { message.textContent='Choisir un style unique pour l’aperçu.'; if(r.status==='ambiguous') renderAmbiguous(r.matches,n=>onPreviewReveal(n.id)); } });
  hide.addEventListener('click',()=>{ const r=match(); if(r.status==='single'){ onHide(r.matches[0].id); message.textContent=`${r.matches[0].name} masquée.`; } else message.textContent='Précisez un style unique à masquer.'; });
  selectStyle.addEventListener('click',()=>onSelect(styleSelect.value)); clear.addEventListener('click',onClearSelection); explored.addEventListener('click',()=>onToggleExplored(styleSelect.value)); reduce.addEventListener('click',()=>onReducedMotion(!stateStore.presentation.reducedMotion));
  function sync(mapState, presentation = stateStore.presentation) { select.value=stateStore.scenario; reduce.setAttribute('aria-pressed', String(presentation.reducedMotion)); list.replaceChildren(); for(const node of nodes.filter(n=>n.functionalType==='capturable')){ const label=document.createElement('label'); const cb=document.createElement('input'); cb.type='checkbox'; cb.checked=discovered.has(node.id); cb.addEventListener('change',()=>cb.checked?onReveal(node.id):onHide(node.id)); label.append(cb,` ${node.name} (${node.id})`); list.append(label);} count.textContent=mapState?`${mapState.visibleNodes.length} nœuds visibles, ${mapState.visibleLinks.length} liens visibles`:''; visualState.textContent=JSON.stringify({revealPendingId:presentation.revealPendingId,selectedId:presentation.selectedId,exploredIds:[...presentation.exploredIds],reducedMotion:presentation.reducedMotion},null,2); }
  container.append(panel); return { sync };
}
