import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import { buildSearchIndex, findDebugStyleMatches } from '../../src/domain/search.js';
const nodes=JSON.parse(fs.readFileSync('data/taxonomy-nodes.json')); const aliases=JSON.parse(fs.readFileSync('data/aliases.json')); const index=buildSearchIndex(nodes,aliases);
test('recherche publique exacte et alias',()=>{for (const q of ['West Coast IPA','west coast ipa','WCIPA','NEIPA','APA','IPL','Blanche belge']) assert.equal(findDebugStyleMatches(q,index).status,'single',q);});
test('recherche publique sans liste révélatrice',()=>{assert.equal(findDebugStyleMatches('inconnu',index).status,'none'); assert.equal(findDebugStyleMatches('IPA',index).status,'single');});
test('shell applicatif documenté dans le HTML',()=>{const html=fs.readFileSync('index.html','utf8'); assert(html.includes('global-navigation-root')); assert(html.includes('map-static-canvas')); assert(html.includes('map-dynamic-canvas')); assert(html.includes('map-accessibility-layer'));});

test('structure HTML V0.2.2',()=>{const html=fs.readFileSync('index.html','utf8'); assert(!html.includes('<header')); for (const needle of ['app-shell','view-root','global-navigation-root','zythosphere-search-slot','map-toolbar-slot','map-static-canvas','map-dynamic-canvas']) assert(html.includes(needle), needle); assert(!html.includes('class="legend"')); assert(!html.includes('bottom-ui'));});

test('navigation globale SVG V0.2.2',()=>{const js=fs.readFileSync('src/ui/bottom-navigation.js','utf8'); for (const label of ['Zythosphère','Brassopédie','Dégustations','Progression']) assert(js.includes(label)); assert.equal((js.match(/viewBox="0 0 24 24"/g)||[]).length >= 1, true); assert(js.includes('aria-current')); assert(js.includes('currentColor')); assert(!/[🍺📚]/.test(js)); assert(!js.includes('<circle cx="12" cy="12" r="7"></circle>'));});

test('recherche et contrôles déplacés',()=>{const reveal=fs.readFileSync('src/ui/reveal-bar.js','utf8'); const toolbar=fs.readFileSync('src/ui/map-toolbar.js','utf8'); assert(reveal.includes('style-reveal-input')); assert(reveal.includes('sr-only')); assert(reveal.includes('aria-live="polite"')); assert(!reveal.includes('Prototype : découvertes')); for (const label of ['Zoom avant','Zoom arrière','Recentrer la carte','Vue générale','Réduire les animations']) assert(toolbar.includes(label));});

test('fond mousse et canvas transparent',()=>{const tokens=fs.readFileSync('styles/tokens.css','utf8'); const mapCss=fs.readFileSync('styles/map.css','utf8'); const canvas=fs.readFileSync('src/canvas/canvas-map-renderer.js','utf8'); for (const token of ['--foam-base','--foam-light','--beer-amber','--nav-bg']) assert(tokens.includes(token)); assert(mapCss.includes('radial-gradient(circle at 16% 22%')); assert(!canvas.includes('createRadialGradient')); assert(!canvas.includes('fillRect(0,0,size.width,size.height)'));});
